### ISSUE TITLE
Suggestion for improvements

### ISSUE THREAD

**Issue by guilherme15990** [gristlabs/grist-desktop#10]
I'm using Grist daily at the charity where I work and some little things have caught my attention:

- 1. The application does not open with window maximized by default. On Windows this is not a problem, but on the Linux version I couldn't find a solution.

- 2. The system keeps the order in which the columns were created, ignoring the order in which they were rearranged by the user. This causes the generated cards to be "messy", especially when the table has a lot of data.

- 3. When trying to attach a file, I couldn't find an indicator that accurately indicated the file size limit. The bar exists, but no indicator is shown. Maybe it's an electron compilation problem.

- 4. There are no labels to separate the tables, being necessary to create an "empty" table to group others in order to create a hierarchy.

- 5. The fact that aggregated tables always open expanded.

GRIST really is a fantastic piece of software, but among these suggestions, number 1, 2, 3 have a huge impact on day-to-day productivity

**Comment by SleepyLeslie** [comment]
Thanks for the feedback and sorry for our delayed response.

Your 1st point can be addressed by persisting window size as suggested in #28, hence will be tracked there.

Your other points are not specific to Grist Desktop, and would require changes to Grist Core. Could you open corresponding issues under the [grist-core](https://github.com/gristlabs/grist-core) repo instead?

**Comment by paulfitz** [comment]
Don't quite know where to add this information, but there's a new option for signing on Windows that I wasn't aware of https://news.ycombinator.com/item?id=40715250
