### ISSUE TITLE
Flatpak packaging

### ISSUE THREAD

**Issue by Victor239** [gristlabs/grist-desktop#16]
Flatpak is the most popular way to ship Linux desktop apps these days, would love to see it on Flathub soon.

**Comment by SleepyLeslie** [comment]
We use [electron-builder](https://www.electron.build) to build Grist Desktop. Unfortunately, it currently [doesn't support](https://www.electron.build/configuration/flatpak.html) publishing to Flatpak repositories. We will consider adding a Flatpak build once electron-builder supports it.

**Comment by Summertime** [comment]
Flathub itself does have information on how to package electron/electron-builder based applications https://docs.flatpak.org/en/latest/electron.html

**Comment by sirrahn** [comment]
I am using Grist Desktop on linux and also think that a flatpak version would make it much better in terms of ease and integration. 

It would also be seen by many more people through distributions if it was a flatpak (Eg the Fedora software app, etc). I would want to see it included in their repository!

**Comment by slimhk45** [comment]
+1 for a Flatpak distribution. I use SecureBlue (a hardened Fedora Atomic distro), and it doesn't support AppImages out of the box because its dependencies are unmaintained (fuse2).
